name: Build and Publish Docker Images to Docker Hub
on:
  [workflow_dispatch]

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker build ./python-fastapi-s3aws-api/ -t cr4tus/devops-back-end:latest

      - name: Push Docker Images to Docker Hub
        run: |
          docker login -u cr4tus -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push cr4tus/devops-back-end:latest
